###
# @name QuerySecurities
GET http://localhost:4004/odata/v4/catalog/Securities

### 
# @name CreateNewSecurity
POST http://localhost:4004/odata/v4/catalog/Securities
Content-Type: application/json

{
  "isin": "JP3756600007",
  "wkn": "864009",
  "ticker": "NTO.F",
  "name": "Nintendo",
  "currency": "EUR"
}

### 
# @name QuerySecuritiesAgain
GET http://localhost:4004/odata/v4/catalog/Securities

@security_isin = {{ QuerySecuritiesAgain.response.body.value[1].isin }}

### 
# @name ReadSpecificSecurityEntity
GET http://localhost:4004/odata/v4/catalog/Securities('{{security_isin}}')

### 
# @name DeleteSpecificBookEntity
DELETE http://localhost:4004/odata/v4/catalog/Securities('{{security_isin}}')